baseURL = "https://noflux.nostr.technology/"
languageCode = "en-us"
title = "Noflux"
disableKinds = ["taxonomy", "term", "sitemap"]
enableRobotsTXT = true

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
codeFences = false

[author]
name = "fiatjaf"

[outputs]
page = ["HTML"]
home = ["HTML"]
section = ["HTML"]
